deploy_or_rollback_or_uninstall: deploy
helm_chart_version: 1.1.1

deploy:
  cluster1:
    namespace1:
      - plcm/activities/payment-msg-client-prepare-activity
    namespace2:   
      - plcm/activities/payment-msg-ebap-dispatch-activity  
  cluster2:
    namespace3:
      - plcm/activities/payment-msg-client-prepare-activity   
    namespace4:
      - plcm/activities/payment-msg-ebap-dispatch-activity  
