# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vishnu3121999/openjdk:17-slim
      # If your Dockerfile sets up a non-root user (e.g., 'runner') and proper workspace permissions,
      # you might add options to ensure the correct user is used. For example:
      # options: --user runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bazel tests
        run: |
          # Run your test suite (for example, using Bazel)
          echo "hi"
          bazel test //...
